---
# 5d. Add two new variables directly into your playbook.
# These variables should correspond to ntp_server1 and ntp_server2
# and have values of 20.20.20.20 and 20.20.20.30, respectively.

- hosts: cisco
  tasks: 
#  - name: Using debug module to print out Ansible variables for the cisco group
#    debug:
#      msg: "{{ ansible_host }}"
#  - name: Print out local_as_number variable with debug module
#    debug:
#      msg: "{{ local_as_number }}"
#   - name: Print out local_as number variable with debug module
#     debug:
#       msg: "{{ remote_as_number }}"
    - name: Print out ntp server details for pynet-rtr1 using debug module
      debug:
        msg: "{{ ntp_server1 }}"
    - name: Print out ntp server details for pynet-rtr2 using debug module
      debug:
        msg: "{{ ntp_server2 }}"
...
