---
# Using Ansible, configure three VLANs on the Arista switch specifying both:
# the VLAN IDs and the VLAN names.  For the VLAN IDs randomly pick three 
# numbers between 100 and 999.
# Notice that in order to execute this playbook copy it to ~/ANSIBLE folder.

- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: create FIRST VLAN
      eos_vlan: name=FIRST vlanid=101
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: create SECOND VLAN
      eos_vlan: name=SECOND vlanid=111
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: create THIRD VLAN
      eos_vlan: name=THIRD vlanid=121
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https
