---
# Use Ansible to restore your 'primary interface' (Ethernet4) back to 
# the following state:
# description: <none>
# switchport mode: access
# access VLAN: 1
# trunk allowed VLANs: all
# Also use Ansible to remove the three VLANs that you configured.
# Noice, this playbook needs to be run in ~/ANSIBLE/ directory.

- name: Arista-Ansible module to remove all previous switch configurations
  hosts: arista

  tasks:
    - name: configuring Ethernet4 for access mode, VLAN1
      eos_switchport: name=Ethernet4 mode=access access_vlan=1 trunk_allowed_vlans=1-4094
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: resetting Ethernet4 description to default
      eos_interface: name=Ethernet4 description=''
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Removing VLANs (FIRST, SECOND and THIRD) using FOR loop
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}} state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {name: FIRST, vlanid: 101}
        - {name: SECOND, vlanid: 111}
        - {name: THIRD, vlanid: 121}
