---
# 5c. Add a "Host Var" for the variable remote_as_number. 
# This variable should have a value of 200 for pynet-rtr1 and
# a value of 300 for pynet-rtr2.
# Once again use the debug task from exercise5 to verify you properly
# see this variable when you execute a playbook. 

remote_as_number: 200
...
